### ISSUE TITLE
Materia theme Input formating in IE 11

### ISSUE THREAD

**Issue by gdandy** [thomaspark/bootswatch#657]
The inputs are not formatted properly in IE 11 with the Materia theme.  The placeholders and spacing is all off.  I know IE sucks.  I checked a few other themes like Darkly and they looked fine in IE 11.

Thanks,
Andy

**Comment by thomaspark** [comment]
Hey Andy, I pushed a fix for this in 51254dd. Should look like this now:

![capture](https://cloud.githubusercontent.com/assets/900407/25773308/50e67080-3249-11e7-866a-a465e6d22117.PNG)

**Comment by gdandy** [comment]
Thanks for looking into it Thomas.  I'm still seeing some vertical spacing issues with inputs in IE 11 with that code change.

![2017-05-07_9-11-16](https://cloud.githubusercontent.com/assets/587590/25781893/2ac95432-3305-11e7-94bb-306f593c7bff.png)
![2017-05-07_9-11-57](https://cloud.githubusercontent.com/assets/587590/25781898/448d0a30-3305-11e7-91b1-cc9061f0388e.png)

**Comment by thomaspark** [comment]
It hasn't been updated on the preview site yet, but if you try the version here, it should hopefully look better: https://github.com/thomaspark/bootswatch/tree/v4/materia

**Comment by gdandy** [comment]
Hmm, still doesn't look like it's fixed in IE when I use that source.  I had used the files from the commit to preview in my last review.

**Comment by thomaspark** [comment]
Just pushed another change to that branch, let me know if that works for you.

**Comment by gdandy** [comment]
Now it's fixed.  Thanks!  And thanks for all your work!
